### ISSUE TITLE
URL for Bing and google return 401s and 400's respectively

### ISSUE THREAD

**Issue by PaulGH** [jamesmontemagno/app-imagesearch-cogs#1]
Hi,  

Just downloaded the code.  I was able to build and run (after adding the `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` element to all 3 projects.

However, when running the iOS app using the Bing or google calls, they both fail.  Is there a different URL we should be using?

Thanks

**Comment by jamesmontemagno** [comment]
Did you add your API keys from the README?
